apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: db
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: db
      tier: db
  template:
    metadata:
      labels:
        app: db
        tier: db
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        env:
         - name: MYSQL_ROOT_PASSWORD
           valueFrom:
             secretKeyRef:
               name: password
               key: pass
         - name: MYSQL_DATABASE
           value: db
        ports:
        - containerPort: 3306