apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp
  labels:
    app: http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http
  template:
    metadata:
      labels:
        app: http      
    spec:
      containers:
      - name: wordpress
        image: wordpress:latest
        env:  
         - name: WORDPRESS_DB_HOST
           value: wp-service
         - name: WORDPRESS_DB_PASSWORD 
           valueFrom:
            secretKeyRef:
              name: password
              key: pass      
         - name: WORDPRESS_DB_NAME
           value: db
         - name: WORDPRESS_DB_USER
           value: root
        ports:
        - containerPort: 80